name: Build AI_Kolbasa Multihack

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Add MSBuild to PATH
      uses: microsoft/setup-msbuild@v2

    - name: Download MinHook Source
      run: |
        powershell -Command "Invoke-WebRequest -Uri https://github.com/TsudaKageyu/minhook/archive/refs/heads/master.zip -OutFile minhook.zip"
        powershell -Command "Expand-Archive -Path minhook.zip -DestinationPath ."
        powershell -Command "Rename-Item -Path minhook-master -NewName minhook"

    - name: Download ImGui Source
      run: |
        powershell -Command "Invoke-WebRequest -Uri https://github.com/ocornut/imgui/archive/refs/heads/master.zip -OutFile imgui.zip"
        powershell -Command "Expand-Archive -Path imgui.zip -DestinationPath ."
        powershell -Command "Rename-Item -Path imgui-master -NewName imgui"

    - name: Copy ImGui DX11 Backends to root
      run: |
        powershell -Command "Copy-Item -Path imgui/backends/imgui_impl_dx11.* -Destination imgui/"
        powershell -Command "Copy-Item -Path imgui/backends/imgui_impl_win32.* -Destination imgui/"

    - name: Build Solution in Release x64
      run: msbuild YourProjectName.sln -p:Configuration=Release -p:Platform=x64

    - name: Upload Compiled DLL Artifact
      uses: actions/upload-artifact@v4
      with:
        name: AI_Kolbasa_Release_x64
        path: |
          **/Release/*.dll
          **/*.dll
